name: Java CI with Maven

on:
  push:
  pull_request:
  

permissions: read-all
jobs:     
  build:
    #The type of container the application will run in.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Step 1 - Checkout the main branches from Github
      uses: actions/checkout@v3
    
    - name: Step 2 - Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build and test with Maven
      run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout the main branches from Github
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Step 3 - Run tests with Maven
      run: mvn test
